### PR TITLE
Tidies up the query formatters

### PR DESCRIPTION
**Pull request by devilgate**
Removed a couple of unused classes and moved one.

This isn't as big as it looks: moving a class affects all the ones that import it.

### CODE REVIEW

**Comment by peterhambly** [comment]
Compile error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project rifGenericLib
rary: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Peter/Documents/GitHub/rapidInquiryFacility/rifGenericLibrary/src/main/java/org/sahsu/rif/generic/datastorage/pg/P
GUserDatabaseConnections.java:[13,41] cannot find symbol
[ERROR] symbol:   class SQLQueryUtility
[ERROR] location: package org.sahsu.rif.generic.datastorage
[ERROR] /C:/Users/Peter/Documents/GitHub/rapidInquiryFacility/rifGenericLibrary/src/main/java/org/sahsu/rif/generic/datastorage/ms/M
SUserDatabaseConnections.java:[14,41] cannot find symbol
[ERROR] symbol:   class SQLQueryUtility
[ERROR] location: package org.sahsu.rif.generic.datastorage
```

**Comment by peterhambly** [comment]
Error still present. Caused by commit b503382769398b9afc89f68994e4f32782a45e6f which has removed  *org.sahsu.rif.generic.datastorage.SQLQueryUtility*

**Comment by devilgate** [comment]
I committed a change that fixed that a week ago. See the screenshot below. And I remember pushing it, because you were here and I told you. But maybe something went wrong and it didn't make it. Anyway, I've merged and pushed everything, so please try again now.

screen shot 2018-06-18 at 10 06 51
